
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://huoxkrkgblayizxqrkkd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1b3hrcmtnYmxheWl6eHFya2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NzYzNjEsImV4cCI6MjA2MjQ1MjM2MX0.6m_T7j4CUrOZnNaSNoQLwOFb2YCpxccYOejBoRIZL9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
