name: Instalar Supabase CLI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Baixar e instalar Supabase CLI
        run: |
          ARCH=$(uname -m)
          VERSION=v1.154.2
          FILE=supabase_${VERSION}_linux_${ARCH}.tar.gz
          wget https://github.com/supabase/cli/releases/download/${VERSION}/${FILE}
          tar -xzf ${FILE}
          sudo mv supabase /usr/local/bin/supabase

      - name: Verificar versão do Supabase CLI
        run: supabase --version
