# .github/workflows/supabase-cli.yml

name: Instalar Supabase CLI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar Supabase CLI
        run: |
          ARCH=$(uname -m)
          VERSION="1.154.2"

          if [ "$ARCH" == "x86_64" ]; then
            FILE="supabase-cli-linux-amd64"
          elif [ "$ARCH" == "aarch64" ]; then
            FILE="supabase-cli-linux-arm64"
          else
            echo "Arquitetura não suportada: $ARCH"
            exit 1
          fi

          echo "Baixando Supabase CLI versão $VERSION para $ARCH"
          curl -sL https://github.com/supabase/cli/releases/download/v$VERSION/$FILE -o supabase
          
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase

          echo "Supabase CLI instalado com sucesso:"
          supabase --version
