name: Baixar e Instalar Supabase CLI

on:
  push:
    branches:
      - main

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código-fonte
        uses: actions/checkout@v2

      - name: Baixar e instalar Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-amd64 -o ./supabase-cli
          chmod +x ./supabase-cli
          sudo mv ./supabase-cli /usr/local/bin/supabase

      - name: Verificar instalação do Supabase CLI
        run: supabase --version
