name: Instalar Supabase CLI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Baixar e instalar Supabase CLI
        run: |
          ARCH=$(uname -m)
          echo "Baixando Supabase CLI versão 1.154.2 para $ARCH"
          curl -sL https://github.com/supabase/cli/releases/download/v1.154.2/supabase_1.154.2_linux_${ARCH}.tar.gz | tar -xz
          sudo mv supabase /usr/local/bin/supabase

      - name: Verificar versão do Supabase CLI
        run: supabase --version
