name: Baixar e Instalar Supabase CLI

on:
  push:
    branches:
      - main

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código-fonte
        uses: actions/checkout@v2

      - name: Verificar arquitetura do sistema
        run: |
          echo "Arquitetura do sistema: $(uname -m)"  # Verifica a arquitetura (x86_64 ou ARM)

      - name: Excluir qualquer arquivo supabase existente
        run: |
          if [ -f /usr/local/bin/supabase ]; then
            echo "Excluindo arquivo supabase existente"
            sudo rm /usr/local/bin/supabase
          fi

      - name: Baixar Supabase CLI com curl detalhado
        run: |
          # Baixar a versão adequada do Supabase CLI dependendo da arquitetura
          if [ "$(uname -m)" == "x86_64" ]; then
            echo "Baixando supabase-cli para arquitetura x86_64"
            curl -v -L https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-amd64 -o ./supabase-cli
          elif [ "$(uname -m)" == "aarch64" ]; then
            echo "Baixando supabase-cli para arquitetura ARM"
            curl -v -L https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-arm64 -o ./supabase-cli
          else
            echo "Arquitetura não suportada: $(uname -m)"
            exit 1
          fi

          # Verificar tipo de arquivo logo após o download
          file ./supabase-cli  # Verifica se é um binário executável

          # Mostrar o conteúdo das primeiras linhas para inspeção
          head -n 10 ./supabase-cli  # Exibe as primeiras 10 linhas do arquivo para diagnóstico

      - name: Tornar Supabase CLI executável
        run: |
          # Caso o arquivo seja válido
          chmod +x ./supabase-cli
          sudo mv ./supabase-cli /usr/local/bin/supabase

      - name: Verificar instalação do Supabase CLI
        run: supabase --version
