name: Instalar Supabase CLI

on:
  workflow_dispatch:

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Baixar e instalar o Supabase CLI
        run: |
          echo "Baixando o Supabase CLI..."

          # Baixar a versão específica do CLI
          curl -sL https://github.com/supabase/cli/releases/download/v1.154.2/supabase_1.154.2_linux_amd64.tar.gz -o supabase-cli.tar.gz

          # Remover arquivos antigos que possam causar conflito
          rm -f supabase
          rm -rf supabase-cli

          # Extrair o CLI
          tar -xzf supabase-cli.tar.gz

          # Tornar executável e mover para /usr/local/bin
          chmod +x supabase
          sudo
