name: Baixar e Instalar Supabase CLI

on:
  push:
    branches:
      - main

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código-fonte
        uses: actions/checkout@v2

      - name: Verificar arquitetura do sistema
        run: |
          echo "Arquitetura do sistema: $(uname -m)"  # Verifica a arquitetura (x86_64 ou ARM)

      - name: Excluir qualquer arquivo supabase existente
        run: |
          if [ -f /usr/local/bin/supabase ]; then
            echo "Excluindo arquivo supabase existente"
            sudo rm /usr/local/bin/supabase
          fi

      - name: Baixar Supabase CLI com versão confiável
        run: |
          echo "Baixando o Supabase CLI..."
          curl -L https://github.com/supabase/cli/releases/download/v1.0.1/supabase-cli-linux-amd64 -o ./supabase-cli
          
          # Verificar se o arquivo foi baixado corretamente
          if [ ! -f ./supabase-cli ]; then
            echo "Erro: Arquivo supabase-cli não foi baixado corretamente."
            exit 1
          fi

          # Verificar tipo de arquivo logo após o download
          file ./supabase-cli  # Verifica se é um binário executável

          # Mostrar o conteúdo das primeiras linhas para inspeção
          echo "Exibindo as primeiras 10 linhas do arquivo para diagnóstico:"
          head -n 10 ./supabase-cli  # Exibe as primeiras 10 linhas do arquivo para diagnóstico

      - name: Tornar Supabase CLI executável
        run: |
          chmod +x ./supabase-cli
          sudo mv ./supabase-cli /usr/local/bin/supabase

      - name: Verificar instalação do Supabase CLI
        run: supabase --version
