name: Instalar Supabase CLI

on:
  workflow_dispatch:

jobs:
  install_supabase_cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Baixando e Instalando Supabase CLI
        run: |
          echo "Baixando o Supabase CLI..."
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-x64.tar.gz -o supabase.tar.gz
          mkdir -p supabase-cli
          tar -xzf supabase.tar.gz -C supabase-cli
          sudo mv supabase-cli/supabase /usr/local/bin/supabase
          supabase --version
