name: Gerar Types do Supabase

on:
  workflow_dispatch:

jobs:
  gerar-types:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Baixar e instalar Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-amd64 -o supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin/supabase
          supabase --version

      - name: Criar pasta se necessário
        run: mkdir -p ./integrations/supabase

      - name: Gerar types do Supabase
        run: supabase gen types typescript --project-id asjntdjqbvylbohmico --schema public > ./integrations/supabase/types.ts
